name: Deploy on cloudflare
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '2.1.15'
